- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Science
    time: 10h
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  #canBeAntag: false
  antagAdvantage: 75 # Goobstation
  guides: # goobstation
  - Science
  - Command

  goobcoins: 40 #Goob content
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  # <Trauma>
  - External
  - Robotics
  - Genetics
  # </Trauma>
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
